// OGMini-Inspired Product Catalog for HYPER X GT Store
window.HYPERXGT_CATEGORIES = [
  { id: 'crawlers', name: 'Off Road Crawlers', icon: '🧗', count: 21 },
  { id: 'racing', name: 'Racing Cars', icon: '🏎️', count: 24 },
  { id: 'drift', name: 'Drift Cars', icon: '💨', count: 18 },
  { id: 'monster', name: 'Monster Trucks', icon: '🛞', count: 15 },
  { id: 'mini', name: 'Mini RC Cars', icon: '⚡', count: 54 },
  { id: 'collectables', name: 'Scale Collectables', icon: '✨', count: 199 }
];

window.HYPERXGT_BRANDS = [
  { name: 'HYPER X GT', logo: 'hyperxgt_logo.png' },
  { name: 'MINI GT', tag: '1:64 Scale' },
  { name: 'INNO64', tag: 'Detail Diecast' },
  { name: 'POP RACE', tag: 'JDM Legend' },
  { name: 'TARMAC WORKS', tag: 'Motorsport' },
  { name: 'HOT WHEELS PREMIUM', tag: 'Collector' }
];

window.HYPERXGT_PRODUCTS = [
  {
    id: 14695,
    sku: 'HXGT-110-CRAWLER',
    name: 'HYPER X GT 1:10 Pro RC Car 4x4 4WD Rock Climbing Machine',
    brand: 'HYPER X GT',
    category: 'Off Road Crawlers',
    scale: '1:10',
    drive: '4WD',
    speed: '50 KM/H',
    motor: '540 High-Torque Brushed Motor',
    battery: '7.4V 1500mAh Li-ion Dual Battery',
    control: '2.4GHz FHSS 4-Channel Remote (100m Range)',
    dimensions: '42cm × 24.5cm × 18cm',
    material: 'Alloy Chassis Frame, ABS Shell, TPR Rubber Tires',
    weight: '2.1 kg',
    age: '14+ Years',
    sale_price: 32999,
    mrp_price: 38999,
    discount_pct: 15,
    rating: 4.9,
    main_image: 'images/1-10.png',
    status: 'IN STOCK',
    short_description: 'Flagship 1:10 scale 4WD rock crawler with independent metal oil shocks, high torque steering servo, and heavy-duty steel drivetrain built for rugged mountain trails.'
  },
  {
    id: 14696,
    sku: 'HXGT-124-DRIFT',
    name: 'HYPER X GT 1:24 High Speed 4WD Turbo Drift Racer',
    brand: 'HYPER X GT',
    category: 'Drift Cars',
    scale: '1:24',
    drive: '4WD',
    speed: '35 KM/H',
    motor: 'RC180 Micro Brushless Motor',
    battery: '3.7V 800mAh Rechargeable Li-po',
    control: '2.4GHz Pistol Grip Transmitter',
    dimensions: '19cm × 8.5cm × 6cm',
    material: 'High-Impact PVC Body Shell, Slick Drift & Rubber Tires',
    weight: '0.45 kg',
    age: '8+ Years',
    sale_price: 4999,
    mrp_price: 6999,
    discount_pct: 28,
    rating: 4.8,
    main_image: 'images/1-12.png',
    status: 'IN STOCK',
    short_description: 'Precision 1:24 scale 4WD drift car featuring interchangeable slick drift tires, bright LED headlights, and gyro counter-steering stabilizer.'
  },
  {
    id: 14697,
    sku: 'MGT-64-GT3RS',
    name: 'MINI GT 1:64 Porsche 911 GT3 RS Guards Red Diecast',
    brand: 'MINI GT',
    category: 'Collectables',
    scale: '1:64',
    drive: 'RWD',
    speed: 'Display Replica',
    motor: 'Precision Scale Model',
    battery: 'Static Collector Model',
    control: 'Display Base Included',
    dimensions: '7.2cm × 3.1cm × 2.2cm',
    material: 'Die-Cast Zinc Alloy Body, Rubber Tires',
    weight: '0.12 kg',
    age: '14+ Years',
    sale_price: 1499,
    mrp_price: 1899,
    discount_pct: 21,
    rating: 5.0,
    main_image: 'images/1-15.png',
    status: 'PRE-ORDER',
    short_description: 'Official licensed Mini GT 1:64 scale diecast replica of the Porsche 911 GT3 RS in Guards Red with detailed interior, real rubber tires, and acrylic case.'
  },
  {
    id: 14698,
    sku: 'INNO-64-R34-NISMO',
    name: 'INNO64 1:64 Nissan Skyline GT-R R34 Z-Tune Silver',
    brand: 'INNO64',
    category: 'Collectables',
    scale: '1:64',
    drive: 'AWD',
    speed: 'Display Replica',
    motor: 'Precision Scale Model',
    battery: 'Static Collector Model',
    control: 'Display Base Included',
    dimensions: '7.1cm × 3.0cm × 2.1cm',
    material: 'Die-Cast Metal, Photo-Etched Parts',
    weight: '0.14 kg',
    age: '14+ Years',
    sale_price: 2199,
    mrp_price: 2699,
    discount_pct: 18,
    rating: 4.9,
    main_image: 'images/1-20.png',
    status: 'IN STOCK',
    short_description: 'Premium INNO64 1:64 scale diecast collector model of the Nismo GT-R R34 Z-Tune with photo-etched disc brakes, realistic carbon hood, and display pedestal.'
  },
  {
    id: 14699,
    sku: 'POPR-64-EVO6',
    name: 'Pop Race 1:64 Mitsubishi Lancer Evolution VI Tommi Makinen',
    brand: 'POP RACE',
    category: 'Collectables',
    scale: '1:64',
    drive: 'AWD',
    speed: 'Display Replica',
    motor: 'Precision Scale Model',
    battery: 'Static Collector Model',
    control: 'Display Base Included',
    dimensions: '7.0cm × 3.0cm × 2.2cm',
    material: 'Die-Cast Alloy, Opening Engine Hood',
    weight: '0.13 kg',
    age: '14+ Years',
    sale_price: 1899,
    mrp_price: 2299,
    discount_pct: 17,
    rating: 4.9,
    main_image: 'images/1-11.png',
    status: 'IN STOCK',
    short_description: 'Pop Race 1:64 diecast replica of the legendary Evo VI Rally Edition featuring opening bonnet with detailed 4G63 engine bay.'
  },
  {
    id: 14700,
    sku: 'HXGT-114-TRUCK',
    name: 'HYPER X GT 1:14 Brushless 4WD Desert Monster Truck',
    brand: 'HYPER X GT',
    category: 'Monster Trucks',
    scale: '1:14',
    drive: '4WD',
    speed: '65 KM/H',
    motor: '2845 4300KV Brushless Motor',
    battery: '7.4V 2000mAh 30C Li-Po Battery',
    control: '2.4GHz Transmitter with Throttle Dual Rate',
    dimensions: '31cm × 23cm × 13.5cm',
    material: 'Honeycomb Nylon Chassis, Aluminum Heat Sink',
    weight: '1.45 kg',
    age: '14+ Years',
    sale_price: 12999,
    mrp_price: 15999,
    discount_pct: 18,
    rating: 4.9,
    main_image: 'images/1-13.png',
    status: 'IN STOCK',
    short_description: 'Extreme 65 KM/H brushless desert truck equipped with metal differential gears, oil-filled aluminum shocks, and wheelie bar.'
  },
  {
    id: 14701,
    sku: 'TARMAC-64-GTR35',
    name: 'Tarmac Works 1:64 LB-Work Nissan GT-R R35 Matte Black',
    brand: 'TARMAC WORKS',
    category: 'Collectables',
    scale: '1:64',
    drive: 'AWD',
    speed: 'Display Replica',
    motor: 'Precision Scale Model',
    battery: 'Static Collector Model',
    control: 'Display Base Included',
    dimensions: '7.3cm × 3.2cm × 2.1cm',
    material: 'Die-Cast Zinc, Carbon Fiber Livery',
    weight: '0.12 kg',
    age: '14+ Years',
    sale_price: 1999,
    mrp_price: 2499,
    discount_pct: 20,
    rating: 4.8,
    main_image: 'images/1-14.png',
    status: 'IN STOCK',
    short_description: 'Tarmac Works Global64 series Liberty Walk GT-R R35 in Matte Black with widebody aero kit and rubber racing slicks.'
  },
  {
    id: 14702,
    sku: 'HXGT-164-MINIRC',
    name: 'HYPER X GT 1:64 Pro Tabletop Mini RC Racing Car',
    brand: 'HYPER X GT',
    category: 'Mini Cars',
    scale: '1:64',
    drive: '2WD',
    speed: '20 KM/H',
    motor: 'Micro High-RPM Motor',
    battery: '3.7V 100mAh Li-Po (USB C Fast Charge)',
    control: '2.4GHz Full Proportional Remote',
    dimensions: '7.5cm × 3.5cm × 2.5cm',
    material: 'Lightweight ABS Shell, Micro Rubber Tires',
    weight: '0.08 kg',
    age: '8+ Years',
    sale_price: 2499,
    mrp_price: 3499,
    discount_pct: 28,
    rating: 4.7,
    main_image: 'images/1-15.png',
    status: 'IN STOCK',
    short_description: 'Micro proportional 1:64 scale desktop RC car with working LED headlights, underglow lights, and USB-C fast charging.'
  }
];